"""Hub beeps (user request, 2026-09-26): every beep comes from the hub speaker.

The hub only plays sound from a running program. While one of the app's mode
programs runs, the app sends `BEEP` commands (protocol.md). With no program on
the hub it uploads a tiny program that beeps and ends, which takes ~0.5-1 s.
The run and scan tones are played by those programs themselves.
"""

from __future__ import annotations

from app.core.protocol import encode_beep

Tone = tuple[int, int]  # frequency Hz, duration ms

TONES: dict[str, tuple[Tone, ...]] = {
    "connect": ((660, 80), (990, 120)),  # rising pair: link up
    "mode": ((740, 60),),  # Line / Teleop / Drift group button
    "scan": ((880, 80),),  # played by scan_ports.py when it starts
    "black": ((440, 150),),  # calibration sample on black: low
    "white": ((1175, 150),),  # calibration sample on white: high
    "run": ((1000, 100),),  # played by every mode program when it starts
}
MAX_BEEP_MS = 500  # the hub clamps too: a beep blocks its loop while it plays


def beep_commands(name: str) -> list[str]:
    """`BEEP` lines for a running mode program."""
    return [encode_beep(hz, ms) for hz, ms in TONES[name]]


def beep_program(name: str) -> str:
    """MicroPython source that plays the tones and ends."""
    lines = [
        "# Generated by Pybricks Tracker. MicroPython for the hub: beeps and ends.",
        "# No watchdog: this program constructs no motors and never drives.",
        "from pybricks.hubs import InventorHub",
        "",
        "hub = InventorHub()",
    ]
    lines += [f"hub.speaker.beep({hz}, {min(ms, MAX_BEEP_MS)})" for hz, ms in TONES[name]]
    return "\n".join(lines) + "\n"
